import Head from "next/head";
import styles from "../styles/Home.module.css";
import logo from "../assets/Instagram_logo_2022.png";
import Feed from "../components/Feed/Feed.js";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Reels</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href={logo} />
      </Head>
      <Feed />
    </div>
  );
}
